version: 2.1
jobs:
  lint:
    docker:
      - image: circleci/python:3.6.4
          environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            ls -l
            pwd
            pip list

  build:
    machine: true
    steps:
      - checkout
      - run:
          name: start container
          command: docker version && docker image build -t app01 .

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - build
