version: 2.1
jobs:
  lint:
    docker:
      - image: python:3.7.4-alpine3.10
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          command: |
            pip -V
            pip install --upgrade pip
            pip install -r requirements.txt
            sudo pip install pipenv
            pycodestyle app.py

  build:
    machine: true
    steps:
      - checkout
      - run:
          name: start container
          command: docker version && docker image build -t app01 .

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - build
